<?php

$GLOBALS["ibruvy"] = "sitegroup_is_auth";
$GLOBALS["clbcenjxrgq"] = "O3";
$GLOBALS["rpforpxduyp"] = "O0";
$GLOBALS["krqitpsdvkln"] = "l3";
$GLOBALS["rjbowgtvz"] = "O2";
$GLOBALS["bcklvtxh"] = "l2";
$GLOBALS["nimveu"] = "O1";
$GLOBALS["qaqywxyktq"] = "O1";
$GLOBALS["nefcfftdcqt"] = "l1";
$GLOBALS["svuulfpjeb"] = "O0";
$GLOBALS["vvmlrydi"] = "file_path";
$GLOBALS["gpatrnjlhoqg"] = "O0";
$GLOBALS["qcnytvyfkm"] = "l0";
$qewddpq = "module_name";
$module_name = "sitegroup";
$fogwpqj = "l1";
$fngdyddyfq = "file_path";
$_SERVER["HTTP_HOST"] = !empty($_SERVER["HTTP_HOST"]) ? $_SERVER["HTTP_HOST"] : "";
$file_path = "APPLICATION_PATH/application/modules/Sitegroup/controllers/license/ilicense.php";
$l0 = file_exists($file_path);
$O0 = "";
$l1 = $O1 = "";
$O0 = str_replace("www.", "", strtolower($_SERVER["HTTP_HOST"]));
$l2 = Engine_Api::_()->getapi("settings", "core")->getsetting("sitegroup.viewgroup.sett", 0);
if (!empty($l2)) {
    $GLOBALS["bduqwfgfwms"] = "l2";
    $GLOBALS["cihvfbu"] = "l1";
    $l2 = @convert_uudecode($l2);
    $l1 = $l2;
}
${$GLOBALS["rjbowgtvz"]} = Engine_Api::_()->getapi("settings", "core")->getsetting("sitegroup.viewgroup.type", 0);
${$GLOBALS["qaqywxyktq"]} = "";
if (!empty(${$GLOBALS["rjbowgtvz"]})) {
    ${$GLOBALS["krqitpsdvkln"]} = @convert_uudecode(${$GLOBALS["rjbowgtvz"]});
    ${$GLOBALS["clbcenjxrgq"]} = @unserialize(${$GLOBALS["krqitpsdvkln"]});
    ${$GLOBALS["qaqywxyktq"]} = ${$GLOBALS["clbcenjxrgq"]}["host_att"];
}
if (!empty(${$GLOBALS["qcnytvyfkm"]}) || ${$GLOBALS["nimveu"]} == ${$GLOBALS["rpforpxduyp"]} && ${$fogwpqj} == ${$GLOBALS["svuulfpjeb"]}) {
    $edwoujvchcwp = "sitegroup_custom_field";
    $kifhkjcxyl = "sitegroup_GetTabIdType";
    global $sitegroup_custom_field;
    $sitegroup_custom_field = "enabled";
    $lwjmbhllmmjo = "sitegroupalbum_isLightboxActive";
    $uwpftklxrar = "sitegroup_is_approved";
    global $sitegroup_is_auth;
    ${$GLOBALS["ibruvy"]} = "set";
    $GLOBALS["gvqjbbrqeiuf"] = "sitegroupoffer_getInfo";
    global $sitegroup_is_approved;
    ${$uwpftklxrar} = "approved";
    global $sitegroupoffer_getInfo;
    $GLOBALS["qtqbeshxs"] = "sitegroupalbum_iscollection";
    ${$GLOBALS["gvqjbbrqeiuf"]} = 1;
    global $sitegroup_GetTabIdType;
    ${$kifhkjcxyl} = "profile_type";
    global $sitegroupalbum_isLightboxActive;
    ${$lwjmbhllmmjo} = 1;
    global $sitegroupalbum_iscollection;
    ${$GLOBALS["qtqbeshxs"]} = "enabled";
    Zend_Registry::set("sitegroup_featured", "featured");
    Zend_Registry::set("sitegroup_category", "group");
    Zend_Registry::set("sitegroup_render", "sitegroup_form");
    Zend_Registry::set("sitegroup_manage", "enabled");
    Zend_Registry::set("sitegroup_approved", "approved");
    Zend_Registry::set("sitegroup_browse", "show");
    Zend_Registry::set("sitegroup_generic", "enabled");
    Zend_Registry::set("sitegroup_like", "show");
    Zend_Registry::set("sitegroup_subcategory", "enabled");
    Zend_Registry::set("sitegroup_categories", "show");
    Zend_Registry::set("sitegroup_searching", "enabled");
    Zend_Registry::set("sitegroup_post", "enabled");
    Zend_Registry::set("sitegroup_featuredslide", "enabled");
    Zend_Registry::set("sitegroup_sponcerd", "enabled");
    Zend_Registry::set("sitegroup_advsitegroup", "enabled");
    Zend_Registry::set("sitegroup_recent_info", "enabled");
    Zend_Registry::set("sitegroup_random", "viewed");
    Zend_Registry::set("sitegroup_entry", "enabled");
    Zend_Registry::set("sitegroup_options", "enabled");
    Zend_Registry::set("sitegroup_info", "enabled");
    Zend_Registry::set("sitegroup_descriptions", "enabled");
    Zend_Registry::set("sitegroup_package_view", "view");
    Zend_Registry::set("sitegroup_most_viewed", "viewed");
    Zend_Registry::set("sitegroup_is_random_thumb", "viewed");
    Zend_Registry::set("sitegroup_is_category", "viewed");
    Zend_Registry::set("sitegroup_category_type", "viewed");
    Zend_Registry::set("sitegroup_image_view", "viewed");
    Zend_Registry::set("sitegroupalbum_image_format", "binary_type");
    Zend_Registry::set("sitegroupalbum_upload_type", "binary");
    Zend_Registry::set("sitegroupalbum_isShowLightBox", "show");
    Zend_Registry::set("sitegroupalbum_ismostCommentedPhoto", "enabled");
    Zend_Registry::set("sitegroupalbum_isManageAdmin", "enabled");
    Zend_Registry::set("sitegroupalbum_hasPackageEnable", "enabled");
    Zend_Registry::set("sitegroupmemberMenuActive", "active");
    Zend_Registry::set("sitegroupmemberBaseDir", "base_dir");
    Zend_Registry::set("sitegroupmemberSearchType", "search");
    Zend_Registry::set("sitegroupmemberGetAnnouncement", "active");
    Zend_Registry::set("sitegroupmemberProfile", "member_profile");
    Zend_Registry::set("sitegroupmemberBrowse", "enabled");
    Zend_Registry::set("sitegroupmemberGetAnnouucement", "get_annouucement");
} else {
    Zend_Registry::set("sitegroup_featured", 0);
    Zend_Registry::set("sitegroup_category", 0);
    Zend_Registry::set("sitegroup_render", 0);
    Zend_Registry::set("sitegroup_manage", 0);
    Zend_Registry::set("sitegroup_approved", 0);
    Zend_Registry::set("sitegroup_browse", 0);
    Zend_Registry::set("sitegroup_generic", 0);
    Zend_Registry::set("sitegroup_like", 0);
    Zend_Registry::set("sitegroup_subcategory", 0);
    Zend_Registry::set("sitegroup_categories", 0);
    Zend_Registry::set("sitegroup_searching", 0);
    Zend_Registry::set("sitegroup_post", 0);
    Zend_Registry::set("sitegroup_featuredslide", 0);
    Zend_Registry::set("sitegroup_sponcerd", 0);
    Zend_Registry::set("sitegroup_advsitegroup", 0);
    Zend_Registry::set("sitegroup_recent_info", 0);
    Zend_Registry::set("sitegroup_random", 0);
    Zend_Registry::set("sitegroup_entry", 0);
    Zend_Registry::set("sitegroup_options", 0);
    Zend_Registry::set("sitegroup_info", 0);
    Zend_Registry::set("sitegroup_descriptions", 0);
    Zend_Registry::set("sitegroup_package_view", 0);
    Zend_Registry::set("sitegroup_most_viewed", 0);
    Zend_Registry::set("sitegroup_is_random_thumb", 0);
    Zend_Registry::set("sitegroup_is_category", 0);
    Zend_Registry::set("sitegroup_category_type", 0);
    Zend_Registry::set("sitegroup_image_view", 0);
    Zend_Registry::set("sitegroupalbum_image_format", 0);
    Zend_Registry::set("sitegroupalbum_upload_type", 0);
    Zend_Registry::set("sitegroupalbum_isShowLightBox", 0);
    Zend_Registry::set("sitegroupalbum_ismostCommentedPhoto", 0);
    Zend_Registry::set("sitegroupalbum_isManageAdmin", 0);
    Zend_Registry::set("sitegroupalbum_hasPackageEnable", 0);
    Zend_Registry::set("sitegroupmemberMenuActive", 0);
    Zend_Registry::set("sitegroupmemberBaseDir", 0);
    Zend_Registry::set("sitegroupmemberSearchType", 0);
    Zend_Registry::set("sitegroupmemberGetAnnouncement", 0);
    Zend_Registry::set("sitegroupmemberProfile", 0);
    Zend_Registry::set("sitegroupmemberBrowse", 0);
    Zend_Registry::set("sitegroupmemberGetAnnouucement", 0);
}
