
/**

SCRIPT CREATED BY -> BP12
TELEGRAM CHANEL -> https://t.me/bagasp1205cps

**/

function OBFBABYBOTVERSIVIP3($uhlbMRBABYBOT67hhu){$MRBABYBOTbMRBABYBOTMRBABYBOT='a';$66MRBABYBOTbMRBABYBOTlMRBABYBOT='g';$66MRBABYBOT67bMRBABYBOTlMRBABYBOT='C';$1v66MRBABYBOT67bMRBABYBOTlMRBABYBOT='m';$1v66MRBABYBOT67bMRBABYBOTlMRBABYBOT='';$1xm66MRBABYBOT67bMRBABYBOTlMRBABYBOT='Z';$67bMRBABYBOTlMRBABYBOT
