AAAAB///////////////////////////////4At8AAAAAAAAAAAAAAAAAAAAAAAAAAAAf////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///wAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAk///4AAAAAAAAAAAAAAP/////////////+AAAAAAAAAAAAAAA/////////////////7//

