<?php

/* #1: PHPDeobfuscator eval output */ 
    session_start();
    include "connect/connect.php";
    $strSQL = "SELECT * FROM web_setting WHERE settingID = '" . $_GET["settingID"] . "' ";
    $objQuery = mysql_query($strSQL) or die("Error Query [" . $strSQL . "]");
    $objResult = mysql_fetch_array($objQuery);
    $strSQL2 = "select * from windows_size where id=1";
    $objQuery2 = mysql_query($strSQL2) or die("Error Query [select * from windows_size where id=1]");
    $objResult2 = mysql_fetch_array($objQuery2);
    ?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php 
    echo $objResult["title"];
    ?></title><head>
<script>
function checkform ( form )
{

  if (form.username.value == "") {
    form.username.focus();
    return false ;
  }

   if (form.password.value == "") {
    form.password.focus();
    return false ;
  }

  return true ;
}

</script>
<head>
<body onLoad="document.getElementById('username').select()">
<table width="<?php 
    echo $objResult2["w"];
    ?>" height="<?php 
    echo $objResult2["h"];
    ?>" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#E5E5E5">
  
  <tr>
    <td height="5%" align="center" valign="top" bgcolor="E5E5E5"><?php 
    include "header.php";
    ?></td>
  </tr>
  
  <tr>
    <td align="center"  bgcolor="#E5E5E5">
    <table width="50%" border="0" align="center" cellpadding="0" cellspacing="0">
      <tbody>
        <tr>
          <td bgcolor="#99CCFF"><div align="center">เข้าสู่ระบบ - [ขายสินค้าหน้าร้าน]</div></td>
        </tr>
        <tr>
          <td bgcolor="#99CCFF"><form action="user_login.php" method="post" name="form1" id="form1" onSubmit="return checkform(this);">
              <table align="center" border="0" cellpadding="0" cellspacing="0" width="90%">
                <tbody>
                  <tr>
                    <td><table align="center" border="0" cellpadding="5" cellspacing="1" width="100%">
                        <tbody>
                          <tr bgcolor="#DFE6F1">
                            <td width="45%" bgcolor="#E5E5E5"><div align="right">ชื่อผู้ใช้งาน : </div></td>
                            <td width="55%" align="left" bgcolor="#E5E5E5"><input name="username" type="text" id="username" style="width: 100%; height: 50;font: 30pt AngsanaUPC;color: #0000FF ;font-weight: bold" onKeyUp="populateSecondTextBox();" /></td>
                          </tr>
                          <tr bgcolor="#DFE6F1">
                            <td bgcolor="#E5E5E5"><div align="right">รหัสผ่าน : </div></td>
                            <td align="left" bgcolor="#E5E5E5"><input name="password" type="password" id="password" style="width: 100%; height: 50;font: 30pt AngsanaUPC;color: #0000FF ;font-weight: bold" onKeyUp="populateSecondTextBox();" /></td>
                          </tr>
                          <tr bgcolor="#FFEAF4">
                            <td colspan="2" align="center" bgcolor="#E5E5E5"><input name="submit_bt" value="เข้าสู่ระบบ" type="submit" style="width:120px;height:50px" />
                                <input name="reset_bt" value="จบการทำงาน" type="reset" style="width:120px;height:50px"/></td>
                          </tr>
                        </tbody>
                    </table></td>
                  </tr>
                </tbody>
              </table>
          </form></td>
        </tr>
        <tr>
          <td bgcolor="#99CCFF"></td>
        </tr>
      </tbody>
    </table></td>
  </tr>
</table>
</head>
</center>
</body>
</html><?php 
/* END:#1 */
//Generated by Ampare PHP Encoder. For more security please use php protect before encode the php program
